// This file is auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > lib/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          phone: string | null
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          phone?: string | null
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          phone?: string | null
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      roles: {
        Row: {
          id: string
          name: string
          description: string | null
          permissions: Json
          is_default: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          permissions?: Json
          is_default?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          permissions?: Json
          is_default?: boolean
          created_at?: string
        }
      }
      weddings: {
        Row: {
          id: string
          owner_id: string
          bride_name: string
          groom_name: string
          wedding_date: string | null
          city: string | null
          venue: string | null
          description: string | null
          cover_image_url: string | null
          slug: string | null
          status: 'draft' | 'active' | 'completed' | 'cancelled'
          is_published: boolean
          plan_type: 'free' | 'paid'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          bride_name: string
          groom_name: string
          wedding_date?: string | null
          city?: string | null
          venue?: string | null
          description?: string | null
          cover_image_url?: string | null
          slug?: string | null
          status?: 'draft' | 'active' | 'completed' | 'cancelled'
          is_published?: boolean
          plan_type?: 'free' | 'paid'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          bride_name?: string
          groom_name?: string
          wedding_date?: string | null
          city?: string | null
          venue?: string | null
          description?: string | null
          cover_image_url?: string | null
          slug?: string | null
          status?: 'draft' | 'active' | 'completed' | 'cancelled'
          is_published?: boolean
          plan_type?: 'free' | 'paid'
          created_at?: string
          updated_at?: string
        }
      }
      team_members: {
        Row: {
          id: string
          wedding_id: string
          user_id: string | null
          email: string
          role_id: string
          status: 'pending' | 'active' | 'revoked'
          invited_by: string | null
          invited_at: string
          accepted_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          user_id?: string | null
          email: string
          role_id: string
          status?: 'pending' | 'active' | 'revoked'
          invited_by?: string | null
          invited_at?: string
          accepted_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          user_id?: string | null
          email?: string
          role_id?: string
          status?: 'pending' | 'active' | 'revoked'
          invited_by?: string | null
          invited_at?: string
          accepted_at?: string | null
          created_at?: string
        }
      }
      guests: {
        Row: {
          id: string
          wedding_id: string
          name: string
          email: string | null
          phone: string | null
          side: 'bride' | 'groom' | 'both' | null
          tags: string[]
          category: string | null
          plus_one_allowed: boolean
          invite_token: string | null
          invite_sent_at: string | null
          invite_method: string | null
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          name: string
          email?: string | null
          phone?: string | null
          side?: 'bride' | 'groom' | 'both' | null
          tags?: string[]
          category?: string | null
          plus_one_allowed?: boolean
          invite_token?: string | null
          invite_sent_at?: string | null
          invite_method?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          side?: 'bride' | 'groom' | 'both' | null
          tags?: string[]
          category?: string | null
          plus_one_allowed?: boolean
          invite_token?: string | null
          invite_sent_at?: string | null
          invite_method?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      ceremonies: {
        Row: {
          id: string
          wedding_id: string
          name: string
          type: string | null
          date: string | null
          start_time: string | null
          end_time: string | null
          venue: string | null
          address: string | null
          city: string | null
          map_url: string | null
          dress_code: string | null
          description: string | null
          display_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          name: string
          type?: string | null
          date?: string | null
          start_time?: string | null
          end_time?: string | null
          venue?: string | null
          address?: string | null
          city?: string | null
          map_url?: string | null
          dress_code?: string | null
          description?: string | null
          display_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          name?: string
          type?: string | null
          date?: string | null
          start_time?: string | null
          end_time?: string | null
          venue?: string | null
          address?: string | null
          city?: string | null
          map_url?: string | null
          dress_code?: string | null
          description?: string | null
          display_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      rsvps: {
        Row: {
          id: string
          guest_id: string
          ceremony_id: string | null
          status: 'attending' | 'not_attending' | 'maybe'
          guests_count: number
          dietary_restrictions: string | null
          meal_preference: string | null
          message: string | null
          submitted_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          guest_id: string
          ceremony_id?: string | null
          status: 'attending' | 'not_attending' | 'maybe'
          guests_count?: number
          dietary_restrictions?: string | null
          meal_preference?: string | null
          message?: string | null
          submitted_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          guest_id?: string
          ceremony_id?: string | null
          status?: 'attending' | 'not_attending' | 'maybe'
          guests_count?: number
          dietary_restrictions?: string | null
          meal_preference?: string | null
          message?: string | null
          submitted_at?: string
          updated_at?: string
        }
      }
      vendor_categories: {
        Row: {
          id: string
          name: string
          slug: string
          icon: string | null
          display_order: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          icon?: string | null
          display_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          icon?: string | null
          display_order?: number
          created_at?: string
        }
      }
      vendors: {
        Row: {
          id: string
          category_id: string
          name: string
          business_name: string | null
          email: string | null
          phone: string | null
          city: string | null
          state: string | null
          description: string | null
          services: string[]
          price_range: string | null
          rating: number
          review_count: number
          images: string[]
          portfolio_urls: string[]
          website_url: string | null
          instagram_url: string | null
          facebook_url: string | null
          is_verified: boolean
          is_featured: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          category_id: string
          name: string
          business_name?: string | null
          email?: string | null
          phone?: string | null
          city?: string | null
          state?: string | null
          description?: string | null
          services?: string[]
          price_range?: string | null
          rating?: number
          review_count?: number
          images?: string[]
          portfolio_urls?: string[]
          website_url?: string | null
          instagram_url?: string | null
          facebook_url?: string | null
          is_verified?: boolean
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          category_id?: string
          name?: string
          business_name?: string | null
          email?: string | null
          phone?: string | null
          city?: string | null
          state?: string | null
          description?: string | null
          services?: string[]
          price_range?: string | null
          rating?: number
          review_count?: number
          images?: string[]
          portfolio_urls?: string[]
          website_url?: string | null
          instagram_url?: string | null
          facebook_url?: string | null
          is_verified?: boolean
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      vendor_bookings: {
        Row: {
          id: string
          wedding_id: string
          vendor_id: string
          status: 'shortlisted' | 'contacted' | 'negotiating' | 'booked' | 'completed' | 'cancelled'
          quoted_price: number | null
          final_price: number | null
          advance_paid: number
          balance_due: number | null
          contract_url: string | null
          notes: string | null
          booked_by: string | null
          booked_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          vendor_id: string
          status?: 'shortlisted' | 'contacted' | 'negotiating' | 'booked' | 'completed' | 'cancelled'
          quoted_price?: number | null
          final_price?: number | null
          advance_paid?: number
          balance_due?: number | null
          contract_url?: string | null
          notes?: string | null
          booked_by?: string | null
          booked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          vendor_id?: string
          status?: 'shortlisted' | 'contacted' | 'negotiating' | 'booked' | 'completed' | 'cancelled'
          quoted_price?: number | null
          final_price?: number | null
          advance_paid?: number
          balance_due?: number | null
          contract_url?: string | null
          notes?: string | null
          booked_by?: string | null
          booked_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          wedding_id: string
          vendor_booking_id: string | null
          payment_type: 'advance' | 'installment' | 'final' | 'subscription'
          amount: number
          due_date: string | null
          paid_date: string | null
          status: 'pending' | 'paid' | 'overdue' | 'cancelled'
          payment_method: string | null
          transaction_id: string | null
          receipt_url: string | null
          notes: string | null
          reminder_sent_at: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          vendor_booking_id?: string | null
          payment_type: 'advance' | 'installment' | 'final' | 'subscription'
          amount: number
          due_date?: string | null
          paid_date?: string | null
          status?: 'pending' | 'paid' | 'overdue' | 'cancelled'
          payment_method?: string | null
          transaction_id?: string | null
          receipt_url?: string | null
          notes?: string | null
          reminder_sent_at?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          vendor_booking_id?: string | null
          payment_type?: 'advance' | 'installment' | 'final' | 'subscription'
          amount?: number
          due_date?: string | null
          paid_date?: string | null
          status?: 'pending' | 'paid' | 'overdue' | 'cancelled'
          payment_method?: string | null
          transaction_id?: string | null
          receipt_url?: string | null
          notes?: string | null
          reminder_sent_at?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      website_content: {
        Row: {
          id: string
          wedding_id: string
          theme: string
          hero_title: string | null
          hero_subtitle: string | null
          hero_image_url: string | null
          story_title: string
          story_content: string | null
          story_images: string[]
          gallery_images: string[]
          schedule_description: string | null
          contact_email: string | null
          contact_phone: string | null
          hashtag: string | null
          custom_css: string | null
          custom_html: string | null
          seo_title: string | null
          seo_description: string | null
          og_image_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          theme?: string
          hero_title?: string | null
          hero_subtitle?: string | null
          hero_image_url?: string | null
          story_title?: string
          story_content?: string | null
          story_images?: string[]
          gallery_images?: string[]
          schedule_description?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          hashtag?: string | null
          custom_css?: string | null
          custom_html?: string | null
          seo_title?: string | null
          seo_description?: string | null
          og_image_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          theme?: string
          hero_title?: string | null
          hero_subtitle?: string | null
          hero_image_url?: string | null
          story_title?: string
          story_content?: string | null
          story_images?: string[]
          gallery_images?: string[]
          schedule_description?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          hashtag?: string | null
          custom_css?: string | null
          custom_html?: string | null
          seo_title?: string | null
          seo_description?: string | null
          og_image_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      live_updates: {
        Row: {
          id: string
          wedding_id: string
          title: string
          content: string | null
          image_url: string | null
          type: 'announcement' | 'photo' | 'video' | 'milestone'
          is_pinned: boolean
          published_at: string
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          title: string
          content?: string | null
          image_url?: string | null
          type?: 'announcement' | 'photo' | 'video' | 'milestone'
          is_pinned?: boolean
          published_at?: string
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          title?: string
          content?: string | null
          image_url?: string | null
          type?: 'announcement' | 'photo' | 'video' | 'milestone'
          is_pinned?: boolean
          published_at?: string
          created_by?: string | null
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          wedding_id: string | null
          type: string
          title: string
          message: string | null
          link: string | null
          icon: string | null
          is_read: boolean
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          wedding_id?: string | null
          type: string
          title: string
          message?: string | null
          link?: string | null
          icon?: string | null
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          wedding_id?: string | null
          type?: string
          title?: string
          message?: string | null
          link?: string | null
          icon?: string | null
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          wedding_id: string
          user_id: string
          plan_type: 'free' | 'basic' | 'premium'
          status: 'active' | 'cancelled' | 'expired' | 'trial'
          amount: number | null
          currency: string
          billing_cycle: 'monthly' | 'yearly' | 'lifetime' | null
          razorpay_subscription_id: string | null
          razorpay_payment_id: string | null
          started_at: string
          expires_at: string | null
          cancelled_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          user_id: string
          plan_type: 'free' | 'basic' | 'premium'
          status?: 'active' | 'cancelled' | 'expired' | 'trial'
          amount?: number | null
          currency?: string
          billing_cycle?: 'monthly' | 'yearly' | 'lifetime' | null
          razorpay_subscription_id?: string | null
          razorpay_payment_id?: string | null
          started_at?: string
          expires_at?: string | null
          cancelled_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          user_id?: string
          plan_type?: 'free' | 'basic' | 'premium'
          status?: 'active' | 'cancelled' | 'expired' | 'trial'
          amount?: number | null
          currency?: string
          billing_cycle?: 'monthly' | 'yearly' | 'lifetime' | null
          razorpay_subscription_id?: string | null
          razorpay_payment_id?: string | null
          started_at?: string
          expires_at?: string | null
          cancelled_at?: string | null
          created_at?: string
        }
      }
      activity_log: {
        Row: {
          id: string
          wedding_id: string | null
          user_id: string | null
          action: string
          entity_type: string | null
          entity_id: string | null
          details: Json | null
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          wedding_id?: string | null
          user_id?: string | null
          action: string
          entity_type?: string | null
          entity_id?: string | null
          details?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string | null
          user_id?: string | null
          action?: string
          entity_type?: string | null
          entity_id?: string | null
          details?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      wedding_dashboard_stats: {
        Row: {
          wedding_id: string | null
          bride_name: string | null
          groom_name: string | null
          wedding_date: string | null
          total_guests: number | null
          attending_count: number | null
          not_attending_count: number | null
          pending_count: number | null
          booked_vendors: number | null
          total_paid: number | null
          total_pending: number | null
        }
      }
    }
    Functions: {
      generate_wedding_slug: {
        Args: {
          p_bride_name: string
          p_groom_name: string
        }
        Returns: string
      }
      generate_invite_token: {
        Args: Record<string, never>
        Returns: string
      }
      has_permission: {
        Args: {
          p_user_id: string
          p_wedding_id: string
          p_module: string
          p_action: string
        }
        Returns: boolean
      }
    }
  }
}
